"""Sample Natural Earth v5.1.2 ne_110m_land.geojson into a small globe dot mesh.
Usage: python3 scripts/generate-globe-land.py /path/to/ne_110m_land.geojson
Source: https://github.com/nvkelso/natural-earth-vector/blob/v5.1.2/geojson/ne_110m_land.geojson
Natural Earth data is public domain: https://www.naturalearthdata.com/about/terms-of-use/
No network access or third-party Python packages are required by this generator.
"""
import json
import math
from pathlib import Path
import sys


def inside(x, y, ring):
    result = False
    for a, b in zip(ring, ring[1:]):
        if (a[1] > y) != (b[1] > y) and x < (b[0] - a[0]) * (y - a[1]) / (b[1] - a[1]) + a[0]:
            result = not result
    return result


def main():
    source = json.loads(Path(sys.argv[1]).read_text())
    polygons = []
    for feature in source['features']:
        geometry = feature['geometry']
        for rings in ([geometry['coordinates']] if geometry['type'] == 'Polygon' else geometry['coordinates']):
            xs, ys = zip(*rings[0])
            polygons.append((min(xs), min(ys), max(xs), max(ys), rings))
    points = []
    for row in range(100):
        lat = -89.1 + row * 1.8
        count = max(1, round(360 * math.cos(math.radians(lat)) / 1.8))
        for col in range(count):
            lon = -180 + (col + .5 * (row % 2)) * 360 / count
            for west, south, east, north, rings in polygons:
                if west <= lon <= east and south <= lat <= north and inside(lon, lat, rings[0]) and not any(inside(lon, lat, hole) for hole in rings[1:]):
                    points.append([round(lon, 2), round(lat, 2)])
                    break
    target = Path(__file__).resolve().parents[1] / 'Glosify/wwwroot/js/globe-land.js'
    target.write_text('// Generated by scripts/generate-globe-land.py from Natural Earth v5.1.2.\n'
                      '// Public domain; coordinates are [longitude, latitude].\n'
                      'export const landPoints = ' + json.dumps(points, separators=(',', ':')) + ';\n')
    print(f'{len(points)} land points; {target.stat().st_size} bytes')


if __name__ == '__main__':
    main()
